// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_best_defender = "CgkI7pWbnvkSEAIQCA"; // <GPGSID>
        public const string achievement_best_support = "CgkI7pWbnvkSEAIQBQ"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI7pWbnvkSEAIQAw"; // <GPGSID>
        public const string achievement_strategist = "CgkI7pWbnvkSEAIQCg"; // <GPGSID>
        public const string achievement_chemical_warfare = "CgkI7pWbnvkSEAIQDQ"; // <GPGSID>
        public const string achievement_frugal = "CgkI7pWbnvkSEAIQBw"; // <GPGSID>
        public const string achievement_impenetrable_defense = "CgkI7pWbnvkSEAIQBA"; // <GPGSID>
        public const string achievement_knight_slayer = "CgkI7pWbnvkSEAIQCw"; // <GPGSID>
        public const string achievement_destroyer = "CgkI7pWbnvkSEAIQCQ"; // <GPGSID>
        public const string achievement_no_magic = "CgkI7pWbnvkSEAIQDw"; // <GPGSID>
        public const string achievement_sky_is_the_limit = "CgkI7pWbnvkSEAIQAQ"; // <GPGSID>
        public const string achievement_veteran = "CgkI7pWbnvkSEAIQDA"; // <GPGSID>
        public const string achievement_dragon_slayer = "CgkI7pWbnvkSEAIQBg"; // <GPGSID>
        public const string achievement_conqueror = "CgkI7pWbnvkSEAIQAg"; // <GPGSID>

}

